[build]
  # Comando para build (só frontend, backend não é deployado no Netlify)
  command = "npm run build"
  
  # Diretório de publicação (onde está o frontend)
  publish = "dist/public"
  
  # Versão do Node.js
  node_version = "18"

[build.environment]
  # Configurações específicas para o build
  NODE_ENV = "production"
  CI = "true"
  NPM_FLAGS = "--legacy-peer-deps"

# Configurações para SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de segurança
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
# Headers para assets estáticos
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 